# Build and run component governance

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: ComponentGovernanceComponentDetection@0
  name: ComponentGovernanceComponentDetection
  displayName: Component Governance
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
